hash-format = "sha256"

[[files]]
file = "config/betterf3.json"
hash = "5061756c1c85f453dce5620c766f8e7529262525f8b503fc6a16122d58541999"

[[files]]
file = "config/customsplashscreen.json"
hash = "abbaca9b578140568291f5b21144f008d02205bac1b44a54748fdcdd5717ef9b"

[[files]]
file = "config/customsplashscreen/background.png"
hash = "9ad6b17cf9fe7b535f71ca9c7bf87b1a43803523e5d9cd6ca8723b18458848ba"

[[files]]
file = "config/customsplashscreen/progressbar.png"
hash = "e2e0555e30fd677e05570551f36d3a95fd844dcadc62b15e4f901c3442a5e3c7"

[[files]]
file = "config/customsplashscreen/progressbar_background.png"
hash = "6e2fa0adee9638b3e8f36e75ad048f0abb0de2d06b591961c6b2aff943fd46f2"

[[files]]
file = "config/customsplashscreen/square_logo.png"
hash = "7e4897e9f11f9c44aaafdf6c5890803ff5e2908806748f89f1ac596e4e612f42"

[[files]]
file = "config/customsplashscreen/wide_logo.png"
hash = "27b2ea2946ca5b00841ce7d1813b42dfb7e36b12ad50c7c9bea09053ac226cf3"

[[files]]
file = "config/healthbars-client.toml"
hash = "0cfa13856edbd4b15011fef90e4c6262c72f9a221c54dabbba795b8f612552db"

[[files]]
file = "config/waystones-common.toml"
hash = "3ac6a9f58bae25c375abc60bc1080599d16abffea42826c4d58b46bd061d3b66"

[[files]]
file = "config/xaero/lib/common.cfg"
hash = "98f698d96a6d21d830a455b4ad045b70516fa63c298021742d8499e7f0366cd2"

[[files]]
file = "config/xaero/lib/server_profiles/default.cfg"
hash = "d438aea41ca41e93697e059f523686935c0add482f6abe96b532bbf10c6ed80a"

[[files]]
file = "config/xaero/minimap/common.cfg"
hash = "2b49df024c03a369c62a303c72755e7fedeb4f4653ff53a12fd37bd83ccd4ed0"

[[files]]
file = "config/xaero/minimap/server_profiles/default.cfg"
hash = "98b778cc5f0b070a52f8ff54ca56e166e2c8b5f5fdff6a2377bff430666ee534"

[[files]]
file = "config/xaero/world-map/common.cfg"
hash = "0c229eb0daf85bd09af51f21eeeb99497a3bd50a825d5ab1ca695fb21bf6cf9d"

[[files]]
file = "config/xaero/world-map/server_profiles/default.cfg"
hash = "7308d0bd3ec563b5d4b31bff3ad267efd376d92f755e169997d356d4be2e1454"

[[files]]
file = "mods/another-furniture.pw.toml"
hash = "bc5bb9c17c071be6f2abb8f678a1f4f82252971070c8f9b2249169558999dc64"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/automobility.pw.toml"
hash = "1df383137d9ebafa5313df989f2ead4f398a444574eac72a9608f8d425c54b62"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "a9f6cf1a98bc318c887b672aecaff6ffdbf33a6ec06af5f2686b292988d0846e"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "7d1815ec4f2098c4de8b01494373d84da8a5104accd5ae028a2a020595646082"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
hash = "b698ef315db976c1f3dea7a1a65fe9b41e6b5f7b84e59e3bd79a25185094ef32"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "c5833c66008b22b8cdcbc719300e34f9e29a14f5c67789c0498451448ab40296"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "6d4de3bf124c98a61c022477e07c8386940d4804001f5f71b322c9b1b74cb5c2"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "0c345c80310a4bd58c757e43d6060338a85d34eaffcb674a6e9cbf22ecbc9cb8"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "6a492387f6348192bcb9e2ee15f9be142100648ce60080a75f980185cb66ee13"
metafile = true

[[files]]
file = "mods/chunk-loaders.pw.toml"
hash = "4afbe5d16695aa241c61c67d3cc3e0b1259872f3f1380241eeb51176c78fe038"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "0d10973de4466406d116a7c0d976c7c7830e65510ad06b6c83e72b0310e09ad4"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "bf35ad1e9d9046861abb4d0ec6390ea3ac1e75bf39b141f0debd76ab13103e14"
metafile = true

[[files]]
file = "mods/critters-and-companions.pw.toml"
hash = "e27ff19b73147521eff10c9cf0d4d51e36a462d1e67f460ee33287e4356e3fe1"
metafile = true

[[files]]
file = "mods/custom-splash-screen.pw.toml"
hash = "7741c6c2e62a19475087c54cfade92b74d585759ca2746bebcb8cd697cfceb99"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "5b68880f4f5606aa7848d5b1ed9fbb7351a41094a3e5d1090d943b85a5d8bc0a"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "ecc30c21290ac87a732085e16add94a392d4e5dfc0bae5f353975eea51a38a84"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
hash = "1f9cd4e83ced98ba9f8ccff164ce108990e1e8f8f8205b6c549f7db26f1d8c11"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "5be3d07f75f9af8ca2406fc1dc6c3b1765ed07804cfc2614517fa4d6e0cc9e5b"
metafile = true

[[files]]
file = "mods/emi-ores.pw.toml"
hash = "ede11788835bc12a73fa0c1b532139a2dac0ba8e690451b2b887901117f2da4a"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "60e6720aafdfa3304b086f7465917179485a3b2463230505728bd24d54113de3"
metafile = true

[[files]]
file = "mods/enchantment-compat.pw.toml"
hash = "fdffd91bef85d29d5fae455584ac845bf3264ccccf55ca8b7c04e921cdece376"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "f7bb88ccf59b362d533cef59b28b0cab3ef017ad7462dfbe0daae2a0aa30032e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "1fbcec6fae4237b80bf2becfc06fb52a49512821f402b5928b1e2533c73b3142"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "ac1bc64f460718e8038033feedcfd8679c82b055bf45b9d83a6e5e9172d92d5a"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "6ec22733a32cf6e59584fbf2a855e24ea2c05f46026e0799f34f34c0915c8367"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d5799cd3b6ea714602c18546b99ba894e7511835b77803304792468fb7ee187"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "dce0df1d0cb1a7f05811ba502f3a3de0458e0c5154f1b72ae493a339f3866083"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "fe2682e6dbdd4350863e1fcd3f5f211fb437cf7791539bedd50779745beb5232"
metafile = true

[[files]]
file = "mods/grind-enchantments.pw.toml"
hash = "ead92600067d737bd8e7b9bb0b8738f76f0dcea3bd38ce62a2e10ff36ebb6b3f"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "de9842a74bad2677a92f96157171b3108dcacb6a517d395006a1f158d5f46bbb"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "5d38f229a73950cdb9f4b5b34eef9f322d18d09362ad889b2f21e1ac8039b065"
metafile = true

[[files]]
file = "mods/immersive-melodies.pw.toml"
hash = "0a5b03c7ebac217b8f5dc6314039a7338fd786b63146621996632acd9d8dbc8e"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "66bdc905c0db7ecdcca5b85451aca40b872fdb87ea681e270401f418ef4d70e5"
metafile = true

[[files]]
file = "mods/inventory-management.pw.toml"
hash = "40b85465f985bcb300b89018271103db50340ac99949502fc3ff64fb50bcbbae"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "76a2560989102413693bbfbea83570287b3dce4f6ed40dc69aacbd3268633fe7"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c4e45594c8d1ab3dacc3b49142f16fb253178dd31d97cc917bf4a4d54f21e081"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "183d7866328971a71ef6948ef832afc4a43d6b807fdcafe682bc0265d5d651fa"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f7cda152847b85f770b5130db1e1569b5b86ddf09d399377d7133365922a0e08"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
hash = "edde86d78cb403fbe13d3d0008cd94fbafcef5dfeb91874da016d6a796b446de"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "d12b136e07f6f83a1e199aabe430426d19702c9f69e55731092b5d5c2f3fb69f"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "fda06e889a670d153da171cc91f72b3fd26f9228344dae2e36abd3412e0d4f41"
metafile = true

[[files]]
file = "mods/new-health-bars.pw.toml"
hash = "09a9840bdd09a6e5ba36a7f9771f873dff4f90661d0b2af0266d92cc68c37d6f"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "122659d423e8fe5c47b4121bf382e5ceea0ea2c644cd0a08d577cf58ef55d495"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "44a6662d6ac604b2173a8bc426a10c0d621c8ba99d37d1b72525c140c42cb358"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "d3f633dd12cd039a4e58dd398d1c80a324b0d78b9da5b3972b69640bfed211ed"
metafile = true

[[files]]
file = "mods/ribbits.pw.toml"
hash = "e171a4219a5fce5dedd042ebe9b9a8357788f67bbd23569e072b07ac66cefaee"
metafile = true

[[files]]
file = "mods/scarecrows-territory.pw.toml"
hash = "70ba18e8cb1959584d1b00bc1e5720a388f6ce47bb7c687fa4ccecc57343b4d8"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c8bda7e40ba3e14e7e78d1c1f80be842eb6d0acd21fca7b2e6a962bc810b9e46"
metafile = true

[[files]]
file = "mods/skinshuffle.pw.toml"
hash = "f0514cffe232d6c2f33b98176f0b61929caa91786547cda99a85dce28d65969f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "8e009ac87710fbd8f5990285d36ab2b4755e932664ca1bcb9cdfac116d6e3b6d"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "04d5cccae8671610cfcff582f7c1b490ba09622a476b53421cd078eb322f27ae"
metafile = true

[[files]]
file = "mods/trashslot.pw.toml"
hash = "40c60c458184ab9d15fdcc4c610607eca60a1557bbf484fad2942a803d75e0ec"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "e657896d405e82e4539be5c1562f27c666a9d5ca8dad5d30052a402c4916766e"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "860812150cb54f0d9ee1bce7b72798b6cc5f752bb05709f0c60231d054ec281d"
metafile = true

[[files]]
file = "mods/waterframes.pw.toml"
hash = "6eacaa113ef27bddbd9c5966a65fd15a23d68bd826c1d594bfcf6c2380388e74"
metafile = true

[[files]]
file = "mods/watermedia-binaries.pw.toml"
hash = "03c2bc9e406cebc8c70dbdb7cb7e1592e9c41c2d8c2c57ff65f9b1e1501cf4f2"
metafile = true

[[files]]
file = "mods/watermedia-yt-plugin.pw.toml"
hash = "9fa9b86f4975f5995519f284c519482d7aa69f2e3cbc2be208dc43c46998bed6"
metafile = true

[[files]]
file = "mods/watermedia.pw.toml"
hash = "9c14d2011a343872dfa72aee64ef7beb2f9f9e47867807b4b03726cfa8e429b7"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "ad0605e6d75812c78753fbcc98c802701b44ebeb8b2e7648ccb79d9c24dafd82"
metafile = true

[[files]]
file = "mods/xaeros-map-server-utils.pw.toml"
hash = "75b3010e19f9a02570ef3d9a2c8b013c573631402bb0c03f82856e34edcbaf49"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "d7c23c5b2f03df76caa7a4d66ca7961a5a3d05c538e1bda65bfd93fb80a07c5e"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "97a62d0b00bdb7f6a2ba51ad05b2ed8c3ebe06098ce893b3d638d59498addf7f"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "4d98bdba90cdeae788a747bb6fe7d438ba49fdc4eb67c38d4573304eec4a2ef8"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "b769a2f7ef2fa754224c5068491e79d02c0c85e0bc326fc05247f18315cc866b"
metafile = true
