name = "Abobus"
author = "VetaL"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b36cc444fd0fd28f86bb4898c47a58b5fcd03e7884abc848b68bb1383c523a13"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
