name = "Abobus"
author = "VetaL"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "833988388504ab5d7bf075f23564a0b7fdb77c166f121d7f711504f2f77b89d1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
