name = "Abobus"
author = "VetaL"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "624e74199f919aa5d506d6fba8c3ac96dca171d04c4a110c86dee610acd41c51"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
