name = "Abobus"
author = "VetaL"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "551c46065d69894940b8fc8994ef39015180afabaee3db4a40220ef1f942098a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
