name = "Abobus"
author = "VetaL"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f18821e2f2c0c16c0b5ca9d96d8249a87e6fe06097d7f3b37d22f846d9ce1eae"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
